language: go

script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
  - golangci-lint run .
  - go vet .
  - go test .

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
